---
- hosts: all
  tasks:
  - name: Ensure epel repo present
    dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present
  - name: install crisis performance tools
    dnf:
        name: 
        - procps-ng
        - util-linux
        - sysstat
        - iproute
        - numactl
        - perf
        - kernel-tools
        - bcc-tools
        - bpftrace
        - trace-cmd
        - ethtool
        - msr-tools
        - msr-cloud-tools
        state: present
